version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./Frontend/dist/:/usr/share/nginx/html
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    env_file:
      - ./Backend/.env
